name: Build and Release JAR
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: quiz-backend-jar
          path: target/*.jar
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: quiz-backend-jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: quiz-backend-jar/*.jar
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
