name: Build and Release JAR
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Rename JAR file
        run: mv target/*.jar target/quiz-backend.jar
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: quiz-backend-jar
          path: target/quiz-backend.jar
          if-no-files-found: 'error'
          overwrite: 'true'
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: quiz-backend-jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: quiz-backend.jar
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}