name: Trigger Webhook after Release
on:
  workflow_run:
    workflows: ["Build and Release JAR"]
    types:
      - completed

jobs:
  trigger-webhook:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Trigger webhook
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          json: '{"branch": "${{ github.ref_name }}", "repo": "${{ github.repositoryUrl }}"}'